module.exports =  [
    {
      title: 'Dinner at the Zoo',
      awsKey: 'cook',
      description: 'A story about animals that like to cook stuff',
      offset: 1,
      numPages: 11,
      timeRevealedAt: Date.now(),
      timeFirstRead: Date.now(),
      timeLastOpened: 0,
    },
    {
      title: "Rosie's Find",
      awsKey: 'coon',
      description: "A story about a racoon finding her family",
      offset:1,
      numPages: 10,
      timeRevealedAt: Date.now(),
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title: "Baby Bird",
      awsKey: 'bird',
      description: "A story about learning to fly",
      offset:1,
      numPages: 10,
      timeRevealedAt: Date.now(),
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title: "The Ants!",
      awsKey: 'ants',
      description: "It's all about ants.",
      offset:0,
      numPages: 9,
      timeRevealedAt: Date.now(),
      timeFirstRead: Date.now(),
      timeLastOpened: 0,
    },
    {
      title: "Dream",
      awsKey: "dream",
      description: "A story about where you'll go after you fall asleep",
      offset:0,
      numPages: 8,
      timeRevealedAt: Date.now(),
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title: "Sam's Spaceship",
      awsKey: 'sam',
      description: "Sam adventures through space",
      offset:0,
      numPages:10,
      timeRevealedAt: Date.now(),
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title:'My Chores!',
      awsKey:'chores',
      description: "A story about helping",
      offset:0,
      numPages: 6,
      timeRevealedAt: 0,
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title: 'Kitty',
      awsKey:'scratch',
      description: "A story about our cat",
      offset: 0,
      numPages:6,
      timeRevealedAt: 0,
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title: 'Magic Seed',
      awsKey: 'seed',
      description: "A story about my magic seed!",
      offset:0,
      numPages:10,
      timeRevealedAt: 0,
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
    {
      title: "Eli's Pets",
      awsKey: 'whale',
      description: "A story about kitchen swimming",
      offset:1,
      numPages:10,
      timeRevealedAt: 0,
      timeFirstRead: 0,
      timeLastOpened: 0,
    },
  ]
